version: "3.5"

services:
  db: 
    restart: always
    image: postgres:11
    volumes:
      - "db-data:/var/lib/postgresql/data"
    ports:
      - 9432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    networks:
      - default
volumes:
  db-data: